name: 'Dockerize-OceanWATERS'
description: 'Builds a docker image for OceanWATERS and pushes it to docker hub'
inputs:
  base-image:
    required: true
    default: 'ubuntu:18.04'
  ros-distro:
    required: true
    default: melodic
  experimental:
    default: false
  tag-postfix:
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push OceanWATER Builder
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: BASE_DOCKER_IMAGE=${{ inputs.base-image }}, ROS_DISTRO=${{ inputs.ros-distro }}
        push: true
        tags: oceanwaters/builder:ros-${{ inputs.ros-distro }}-desktop-full${{ inputs.tag-postfix }}
        target: oceanwaters_builder
    - name: Build & Push OceanWATER Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: BASE_DOCKER_IMAGE=${{ inputs.base-image }}, ROS_DISTRO=${{ inputs.ros-distro }}
        push: true
        tags: oceanwaters/oceanwaters:ros-${{ inputs.ros-distro }}-desktop-full${{ inputs.tag-postfix }}
        target: oceanwaters_docker